### ISSUE TITLE
Duplicated logic between printers

### ISSUE THREAD

**Issue by mpmenne** [dceu/mario#4]
Keeping code DRY is very important.  Each time code is duplicated it increases the chances that a bug fix won't address all of the duplication and that the bug will persist in the application.

See if you can DRY out your code by consolidating the logic to print a pyramid into a single class.  The printers should only know about the end place where the code is printed; they should not know about how to print.

Hint:  You will want to use `StringBuilder`

**Comment by dceu** [comment]
Implemented all core printing logic with StringBuilder in the toString method of the Pyramid class, using the same loop logic but with StringBuilder.append() instead of System.out.println() or writer.write(). Thanks for the hint. Totally forgot about StringBuilder. Printers now just call this instantiated method from the Pyramid class.
